-- ============================================================
-- Database Schema for DongTen DacLo
-- Tables: training_programs, courses, categories
-- ============================================================

-- 1. Training Programs (Chương trình huấn luyện)
CREATE TABLE IF NOT EXISTS training_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  "order" INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Categories (Danh mục chủ đề)
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  "order" INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Courses (Khóa học chuyên đề)
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  program_id BIGINT REFERENCES training_programs(id) ON DELETE SET NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  course_type TEXT NOT NULL DEFAULT 'Chuyên đề' CHECK (course_type IN ('Chuyên đề', 'Khóa học')),
  format TEXT NOT NULL DEFAULT 'in_person' CHECK (format IN ('in_person', 'online', 'hybrid')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'upcoming', 'completed')),
  status_label TEXT,
  format_label TEXT,
  start_date DATE,
  students_count INTEGER DEFAULT 0,
  "order" INTEGER DEFAULT 0,
  is_featured BOOLEAN DEFAULT false,
  is_new BOOLEAN DEFAULT false,
  location TEXT,
  audience TEXT[] DEFAULT '{}',
  color_hex TEXT DEFAULT 'rgba(139, 26, 26, 0.094)',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_courses_program_id ON courses(program_id);
CREATE INDEX IF NOT EXISTS idx_courses_status ON courses(status);
CREATE INDEX IF NOT EXISTS idx_courses_is_featured ON courses(is_featured);
CREATE INDEX IF NOT EXISTS idx_courses_order ON courses("order");
CREATE INDEX IF NOT EXISTS idx_programs_order ON training_programs("order");

-- Trigger: auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_training_programs_updated_at ON training_programs;
CREATE TRIGGER trg_training_programs_updated_at
  BEFORE UPDATE ON training_programs
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_courses_updated_at ON courses;
CREATE TRIGGER trg_courses_updated_at
  BEFORE UPDATE ON courses
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- Seed Data
-- ============================================================

-- Categories
INSERT INTO categories (name, slug, "order") VALUES
  ('Linh đạo & Giáo huấn', 'linh-dao-giao-huan', 1),
  ('Tình yêu & Hôn nhân', 'tinh-yeu-hon-nhan', 2),
  ('Tâm lý & Kỹ năng sống', 'tam-ly-ky-nang-song', 3),
  ('Cha mẹ — Con cái', 'cha-me-con-cai', 4),
  ('Chữa lành & Đồng hành', 'chua-lanh-dong-hanh', 5),
  ('Nuôi dạy con', 'nuoi-day-con', 6),
  ('Tâm lý — Linh đạo', 'tam-ly-linh-dao', 7),
  ('Hôn nhân & Cặp đôi', 'hon-nhan-cap-doi', 8),
  ('Lịch sử & Giáo lý', 'lich-su-giao-ly', 9)
ON CONFLICT (slug) DO NOTHING;

-- Training Programs
INSERT INTO training_programs (title, slug, description, "order") VALUES
  (
    'Huấn luyện Người Đồng Hành Gia Đình Công Giáo',
    'nguoi-dong-hanh-gia-dinh-cong-giao',
    'Chương trình đào tạo chuyên sâu cho những ai mong muốn trở thành người đồng hành các gia đình theo linh đạo Dòng Tên.',
    1
  ),
  (
    'Huấn luyện Giáo Lý Viên Hôn Nhân',
    'giao-ly-vien-hon-nhan',
    'Đào tạo các giáo lý viên đồng hành các đôi chuẩn bị bước vào Bí tích Hôn Phối với chiều sâu tâm lý và linh đạo.',
    2
  )
ON CONFLICT (slug) DO NOTHING;

-- Courses (Khóa học chuyên đề)
DO $$
DECLARE
  v_hn_id BIGINT; -- Hôn nhân & Cặp đôi
  v_ndc_id BIGINT; -- Nuôi dạy con
  v_tlld_id BIGINT; -- Tâm lý — Linh đạo
  v_lsgl_id BIGINT; -- Lịch sử & Giáo lý
  v_huanluyen_id BIGINT; -- Program 1
  v_linhthao_id BIGINT; -- Program 2 (giả sử có)
  v_mucvu_id BIGINT; -- Mục vụ
BEGIN
  SELECT id INTO v_hn_id FROM categories WHERE slug = 'hon-nhan-cap-doi';
  SELECT id INTO v_ndc_id FROM categories WHERE slug = 'nuoi-day-con';
  SELECT id INTO v_tlld_id FROM categories WHERE slug = 'tam-ly-linh-dao';
  SELECT id INTO v_lsgl_id FROM categories WHERE slug = 'lich-su-giao-ly';
  SELECT id INTO v_huanluyen_id FROM training_programs WHERE slug = 'nguoi-dong-hanh-gia-dinh-cong-giao';

  INSERT INTO courses (title, slug, description, program_id, category_id, course_type, format, status, status_label, format_label, start_date, students_count, "order", is_featured, is_new, location, audience, color_hex) VALUES
    (
      'Chuyên đề "Thai Giáo"',
      'chuyen-de-thai-giao',
      'Giáo dục con từ trong bụng mẹ',
      v_huanluyen_id, v_ndc_id, 'Chuyên đề', 'hybrid', 'active', 'Đang mở', 'Kết hợp',
      '2024-01-20', 45, 1, true, true,
      'Trung tâm Mục vụ Đắc Lộ — 171 Lý Chính Thắng, Q.3 / Online',
      ARRAY['parent', 'couple'],
      'rgba(198, 138, 46, 0.094)'
    ),
    (
      'Nghệ thuật lắng nghe & đối thoại yêu thương trong gia đình',
      'nghe-thuat-lang-nghe',
      'Khóa kỹ năng giao tiếp vợ chồng và cha mẹ — con cái',
      v_huanluyen_id, v_hn_id, 'Khóa học', 'in_person', 'active', 'Đang mở', 'Trực tiếp',
      '2024-02-25', 32, 2, true, false,
      'Trung tâm Mục vụ Đắc Lộ — 171 Lý Chính Thắng, Q.3',
      ARRAY['couple', 'parent'],
      'rgba(47, 110, 84, 0.094)'
    ),
    (
      'Vấn đề giới tính & kỹ năng phòng chống xâm hại cho trẻ',
      'phong-chong-xam-hai-tre',
      'Chuyên đề thời sự cho phụ huynh và giáo viên giáo lý',
      v_huanluyen_id, v_ndc_id, 'Chuyên đề', 'in_person', 'active', 'Đang mở', 'Trực tiếp',
      '2024-03-15', 28, 3, true, false,
      'Trung tâm Mục vụ Đắc Lộ — 171 Lý Chính Thắng, Q.3',
      ARRAY['parent', 'member'],
      'rgba(59, 91, 165, 0.094)'
    ),
    (
      'Gia đình giữa làn sóng công nghệ & trí tuệ nhân tạo',
      'gia-dinh-cong-nghe',
      'Chuyên đề lớn của năm — sống đức tin trong kỷ nguyên số',
      NULL, v_tlld_id, 'Chuyên đề', 'hybrid', 'active', 'Đang mở', 'Kết hợp',
      '2024-04-10', 56, 4, true, true,
      'Trung tâm Mục vụ Đắc Lộ — 171 Lý Chính Thắng, Q.3 / Online',
      ARRAY['couple', 'parent', 'member'],
      'rgba(126, 63, 160, 0.094)'
    ),
    (
      'Gia đình Việt Nam trong buổi đầu Tin Mừng đến Đất Việt',
      'viet-nam-buoi-dau-tin-mung',
      'Lịch sử mục vụ gia đình tại Việt Nam',
      v_huanluyen_id, v_lsgl_id, 'Khóa học', 'in_person', 'active', 'Đang mở', 'Trực tiếp',
      '2024-05-20', 38, 5, true, false,
      'Trung tâm Mục vụ Đắc Lộ — 171 Lý Chính Thắng, Q.3',
      ARRAY['member'],
      'rgba(139, 26, 26, 0.094)'
    ),
    (
      'Khóa Chuẩn bị Hôn nhân Công giáo – Mùa Hè 2026',
      'khoa-tien-hon-nhan-mua-he',
      'Khóa tập trung 8 buổi – kèm cố vấn cá nhân',
      v_huanluyen_id, v_hn_id, 'Khóa học', 'in_person', 'upcoming', 'Sắp khai giảng', 'Trực tiếp',
      '2024-07-20', 0, 7, true, true,
      'Trung tâm Mục vụ Đắc Lộ — 171 Lý Chính Thắng, Q.3',
      ARRAY['premarital', 'couple'],
      'rgba(198, 138, 46, 0.094)'
    ),
    (
      'Linh thao đời thường – 19th Annotation',
      'linh-thao-doi-thuong',
      '34 tuần đồng hành cá nhân theo Linh thao Inhã',
      NULL, v_tlld_id, 'Khóa học', 'hybrid', 'upcoming', 'Sắp khai giảng', 'Kết hợp',
      '2024-08-25', 0, 8, false, true,
      'Trung tâm Mục vụ Đắc Lộ — 171 Lý Chính Thắng, Q.3 / Online',
      ARRAY['member', 'couple'],
      'rgba(126, 63, 160, 0.094)'
    ),
    (
      'Nuôi dạy con tuổi teen – Parenting',
      'nuoi-day-con-tuoi-teen',
      'Đồng hành cùng tuổi vị thành niên trong đức tin và đời sống',
      v_huanluyen_id, v_ndc_id, 'Khóa học', 'online', 'active', 'Đang mở', 'Online',
      '2024-09-15', 67, 9, false, false,
      'Online qua Zoom',
      ARRAY['parent'],
      'rgba(47, 110, 84, 0.094)'
    );
END $$;