import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase/admin';

export async function GET() {
  try {
    // Check if tables exist by querying them
    const { count: programCount, error: programError } = await supabaseAdmin
      .from('training_programs')
      .select('*', { count: 'exact', head: true });

    const { count: courseCount, error: courseError } = await supabaseAdmin
      .from('courses')
      .select('*', { count: 'exact', head: true });

    const tablesExist = !programError && !courseError;
    
    return NextResponse.json({
      status: tablesExist ? 'ready' : 'needs_setup',
      tables: {
        training_programs: programError ? { exists: false, error: programError.message } : { exists: true, count: programCount },
        courses: courseError ? { exists: false, error: courseError.message } : { exists: true, count: courseCount },
      },
    });
  } catch (error: any) {
    return NextResponse.json({ status: 'error', error: error.message }, { status: 500 });
  }
}

export async function POST() {
  try {
    // Read schema SQL inline - tables
    const createProgramsSQL = `
      CREATE TABLE IF NOT EXISTS training_programs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        slug TEXT NOT NULL UNIQUE,
        description TEXT,
        "order" INTEGER DEFAULT 0,
        is_active BOOLEAN DEFAULT true,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
      );
    `;

    const createCategoriesSQL = `
      CREATE TABLE IF NOT EXISTS categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        slug TEXT NOT NULL UNIQUE,
        "order" INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT now()
      );
    `;

    const createCoursesSQL = `
      CREATE TABLE IF NOT EXISTS courses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        slug TEXT NOT NULL UNIQUE,
        description TEXT,
        program_id BIGINT REFERENCES training_programs(id) ON DELETE SET NULL,
        category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
        course_type TEXT NOT NULL DEFAULT 'Chuyên đề' CHECK (course_type IN ('Chuyên đề', 'Khóa học')),
        format TEXT NOT NULL DEFAULT 'in_person' CHECK (format IN ('in_person', 'online', 'hybrid')),
        status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'upcoming', 'completed')),
        status_label TEXT,
        format_label TEXT,
        start_date DATE,
        students_count INTEGER DEFAULT 0,
        "order" INTEGER DEFAULT 0,
        is_featured BOOLEAN DEFAULT false,
        is_new BOOLEAN DEFAULT false,
        location TEXT,
        audience TEXT[] DEFAULT '{}',
        color_hex TEXT DEFAULT 'rgba(139, 26, 26, 0.094)',
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
      );
    `;

    // Execute SQL using raw query
    const { error: err1 } = await supabaseAdmin.rpc('exec_sql', { sql: createProgramsSQL });
    if (err1) {
      // If exec_sql not available, create tables directly
      const { error: errDirect } = await supabaseAdmin.from('training_programs').select('id').limit(1);
      if (errDirect && errDirect.code === '42P01') {
        return NextResponse.json({
          success: false,
          error: 'Cannot create tables automatically. Please run the SQL in src/lib/db/schema.sql manually in Supabase SQL Editor.',
          note: 'Go to https://supabase.com/dashboard/project/zwrvtqvlffknhahdsebxp/sql/new and paste the schema',
        });
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Database setup completed. Run GET /api/setup to verify.',
    });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}